SELECT DISTINCT STUDENT_ID 
FROM EXAM_MARKS 
WHERE STUDENT_ID IN
(SELECT STUDENT_ID 
FROM EXAM_MARKS
GROUP BY STUDENT_ID
HAVING AVG(MARK) = 
(SELECT AVG(MARK) 
FROM EXAM_MARKS
WHERE  STUDENT_ID = 12)
AND COUNT(MARK) = 
(SELECT COUNT(MARK) 
FROM EXAM_MARKS
WHERE  STUDENT_ID = 12))
AND STUDENT_ID IN
(SELECT STUDENT_ID 
FROM EXAM_MARKS 
WHERE MARK IN  
(SELECT MARK 
FROM EXAM_MARKS
WHERE  STUDENT_ID = 12))
AND STUDENT_ID NOT IN 
(SELECT STUDENT_ID 
FROM EXAM_MARKS
WHERE MARK NOT IN 
(SELECT MARK 
FROM EXAM_MARKS
WHERE  STUDENT_ID = 12));