SELECT NAME, STUDENT_ID
FROM STUDENT FIRST, UNIVERSITY SECOND 
WHERE FIRST.CITY != SECOND.CITY
AND FIRST.UNIV_ID = SECOND.UNIV_ID;
SELECT
    FIRST.NAME,
    FIRST.STUDENT_ID
FROM STUDENT FIRST
INNER JOIN UNIVERSITY SECOND
    ON FIRST.UNIV_ID = SECOND.UNIV_ID
WHERE FIRST.CITY != SECOND.CITY;